### ISSUE TITLE
PHP 5.4 required? (Guzzle dependency)

### ISSUE THREAD

**Issue by mitchelgranat** [authy/authy-php#16]
Loading composer repositories with package information

Installing dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

Problem 1

- guzzlehttp/guzzle 5.3.0 requires php >=5.4.0 -> your PHP version (5.3.27) does not satisfy that requirement.

Is there any workaround?

**Comment by robfrawley** [comment]
Solution: Run a version of PHP that hasn't reached "End-of-Life" -- see http://php.net/supported-versions.php

Per the above link, "End of life" (which PHP fell under *beginning over a year ago*) is **"a  release that is no longer supported. Users of this release should upgrade as soon as possible, as they may be exposed to unpatched security vulnerabilities."**

**Comment by dcu** [comment]
PHP 5.3 won't be supported
