### ISSUE TITLE
Broken Tests in the master branch

### ISSUE THREAD

**Issue by castarco** [authy/authy-php#21]
Hi, I've executed the unit tests of this library and I've seen that those tests are broken:

![authy_fails](https://cloud.githubusercontent.com/assets/251364/11536934/f863ba44-991a-11e5-9017-423a43908f6d.png)

**Comment by serargz** [comment]
hey @castarco, tests will be completely fixed in the PR https://github.com/authy/authy-php/pull/40. We'll be publishing a release in the next few days.
