### ISSUE TITLE
Guzzle 6.0 incompatibility

### ISSUE THREAD

**Issue by castarco** [authy/authy-php#22]
It would be nice to release a version of Authy-PHP using Guzzle 6.0 instead of Guzzle 5.0. Actually I can't use this library in the project where I'm working because there is a dependencies conflict.

Composer tries to install a very old version of Authy-PHP because it uses Resty instead of Guzzle, but it lacks a lot of features, so that is not a solution for me.

If "semver" is used for Authy-PHP versioning, then it should be easy to port the current version to Guzzle 6.0 without having to worry about breaking backwards compatibility.

**Comment by serargz** [comment]
@castarco we have merged https://github.com/authy/authy-php/pull/30. It includes Guzzle 6. A new release will be published soon.
