### ISSUE TITLE
GitHub Changes doesn't reflect on packagist

### ISSUE THREAD

**Issue by moiz2050** [authy/authy-php#24]
Hi Authors
i recently installed this library via composer, i am unable to see the updated version that is on git hub for e.g whole `phone verification` methods are missing.

your urgent action required..

**Comment by sato-sh** [comment]
I can confirm this. Installed via composer and a number of methods are missing and not up-to-date with the github repo. Methods such as userStatus() simply don't exist.

**Comment by gboyegadada** [comment]
Wow APRIL 2017 and this is still unresolved.

**Comment by serargz** [comment]
hi @moiz2050, v2.5 in compose includes phone verification methods (https://packagist.org/packages/authy/php#v2.5). We'll be publishing a release in the next few days with some improvements to the library. Sorry for the ridiculously long time to get back to you on this.
