### ISSUE TITLE
Cannot auth using example

### ISSUE THREAD

**Issue by PeterPilley** [authy/authy-php#27]
Trying to auth with PHP library as per example without success

Auth attempts return stream error with url http://verify/{tokencode}/token{key}?force=true

it looks like the api url isnt loading correctly

In the code it is stated as 

```
 $resp = $this->rest->get("verify/{$token}/{$authy_id}", array(

            'query' => $params
        ));

```

It doesnt appear to be loading the $api_url which is listed in AuthyApi.php as https://api.authy.com

If I try and manually run this I get notification that this is the wrong url being api.authy.com/verify is incorrect.

I have checked the python library and it uses api.authy.com/protected/json/verify can you advise what the correct url is?

If I attempt to use this url I get "error_code":"60001","message":"Invalid API key","errors":{"message":"Invalid API key"},"success":false

**Comment by serargz** [comment]
sorry for the (super) late response to this. `api.authy.com` is the correct domain for the Authy api.
