### ISSUE TITLE
Project states PHP 5.3 compatibility but is rife with PHP 5.4 features

### ISSUE THREAD

**Issue by jons** [authy/authy-php#33]
the version 2.5 README and composer.json both state 5.3.0 or greater.

however there are short array declarations `[]` in authy and the version of guzzle it depends on (and still further dependencies PSR, promises), there are `callable` type hints, `static` anonymous functions, anonymous functions with closure over `$this`, use of `curl_reset` in there, and probably other things i have not found yet as i revise the code to work with PHP 5.3.10.

there does not appear to be documentation anywhere noting which specific version of authy to use for PHP prior to 5.4 so now i am stuck trial-and-erroring my way backward through releases.

**Comment by baseq** [comment]
Same here, Authy PHP API not working on PHP 5.3.3.

**Comment by luisuribe** [comment]
This will be fixed by https://github.com/authy/authy-php/pull/41

**Comment by luisuribe** [comment]
PHP version >= 5.6.0 is now needed to use this library.
