### ISSUE TITLE
Update the docs

### ISSUE THREAD

**Issue by hypeJunction** [authy/authy-php#38]
Could you please do the world a favor and update the readme to correspond to the code, so we don't waste our time implmenting a workflow that's no longer valid...

**Comment by stembrain** [comment]
+1

{
    "require": {
        "authy/php": "2.*"
    }
}

does not include the phoneVerification* API calls

**Comment by hypeJunction** [comment]
I talked to their team at Web Summit, and they assured me they are working on finalizing the Authy integration into the Twilio family. Looks like they have a lot on their plate, which I suppose is no excuse when they charge for a product and clients pay for dev time.

**Comment by serargz** [comment]
@hypeJunction we're catching up with issues and PRs on our libraries. Will be publishing a release with some improvements and update the docs withing the next few days. I agree 100% with you, this libraries need some love and we're working on that!
