### ISSUE TITLE
Guzzle Version

### ISSUE THREAD

**Issue by sumbria** [authy/authy-php#39]
Hello there,
Can you please upgrade the guzzle to latest version ? Mostly other packages require _guzzle version to 6.0.0_ or above but **authy** require  5.3.1 or lower.

Thank you.

**Comment by serargz** [comment]
hey @sumbria, we'll publish a release in the next few days with Guzzle 6 support and some other improvements.

**Comment by sumbria** [comment]
@serargz Sounds great. Looking forward to it. Thank you so much

**Comment by cyralterfina** [comment]
Hello @serargz, any updates on this? I am kind of stuck. Thank you very much.

**Comment by serargz** [comment]
@sumbria, @cyralterfina: v3.0 was released. It uses Guzzle 6.x and the tests were fixed. Thanks for your patience.
