### ISSUE TITLE
One touch verification endpoints

### ISSUE THREAD

**Issue by dkusmierek** [authy/authy-php#43]
Hi Guys, 

I started using Authy for our project and I think that you made nice stuff but there is one issue with your library. I want to use one touch verification feature and had to extend your API class to handle this. Is there possible to merge pull request regarding one touch verification in the next release? Will be nice ;)

Best regards :)

**Comment by serargz** [comment]
hey @dkusmierek, yes! we plan to look into this in the next few days. Thanks!

**Comment by chrisdeeming** [comment]
What can we do to speed this along @serargz?

It seems a valid pull request has been made and all that needs to be done is to review, merge and release.

**Comment by luisuribe** [comment]
Merged in https://github.com/authy/authy-php/pull/55
